#!/usr/bin/env node
// Bundles data/*.json into js/data.js (so the site works from file:// with no server)
// and exports Markdown editions to docs/.
// Usage: node tools/build.mjs [--modules-dir <dir>] [--no-docs]
import { readFileSync, writeFileSync, mkdirSync, rmSync, cpSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const MODULE_IDS = ['m1', 'm2-higher', 'm2-lower'];
const LETTERS = ['A', 'B', 'C', 'D'];
const LABELS = { m1: 'Module 1', 'm2-higher': 'Module 2 — Higher route', 'm2-lower': 'Module 2 — Lower route' };
const FILES = { m1: 'M1', 'm2-higher': 'M2-higher', 'm2-lower': 'M2-lower' };

const readJSON = p => JSON.parse(readFileSync(p, 'utf8'));

export function loadAll(modulesDir = join(ROOT, 'data/modules')) {
  const form = readJSON(join(ROOT, 'data/form.json'));
  const taxonomy = readJSON(join(ROOT, 'data/taxonomy.json'));
  const blueprint = readJSON(join(ROOT, 'data/blueprint.json'));
  const modules = {};
  for (const id of MODULE_IDS) modules[id] = readJSON(join(modulesDir, `${id}.json`));
  return { form, taxonomy, blueprint, modules };
}

export function bundleJs(data) {
  return `/* Generated by tools/build.mjs from data/*.json. Do not edit by hand. */\n` +
    `window.SAT_DATA = ${JSON.stringify(data)};\n`;
}

/* ---------- Markdown export ---------- */
const mdInline = s => String(s ?? '')
  .replace(/_{6,}/g, '\\_\\_\\_\\_\\_\\_')
  .replace(/\{u\}/g, '<u>').replace(/\{\/u\}/g, '</u>');
const mdParas = s => String(s ?? '').split(/\n{2,}/).map(p => mdInline(p).replace(/\n/g, '  \n')).join('\n\n');
const mdCell = s => mdInline(String(s)).replace(/\|/g, '\\|');

export function stimulusMd(st) {
  const out = [];
  if (st.attribution) out.push(`*${mdInline(st.attribution).replace(/\*/g, '')}*`);
  if (st.title) out.push(`**${mdInline(st.title)}**`);
  switch (st.type) {
    case 'poem':
      out.push(String(st.text).split('\n').map(l => '> ' + (mdInline(l) || '&nbsp;')).join('  \n'));
      break;
    case 'paired':
      out.push('**Text 1**', mdParas(st.text1), '**Text 2**', mdParas(st.text2));
      break;
    case 'notes':
      out.push(mdInline(st.intro || 'While researching a topic, a student has taken the following notes:'));
      out.push((st.notes || []).map(n => '- ' + mdInline(n)).join('\n'));
      break;
    case 'table':
      out.push(`**${mdInline(st.table.caption)}**`);
      out.push('| ' + st.table.columns.map(mdCell).join(' | ') + ' |\n|' + st.table.columns.map(() => '---').join('|') + '|\n' +
        st.table.rows.map(r => '| ' + r.map(mdCell).join(' | ') + ' |').join('\n'));
      if (st.text) out.push(mdParas(st.text));
      break;
    case 'chart': {
      const c = st.chart;
      out.push(`**${mdInline(c.caption)}** (bar chart; y-axis: ${mdInline(c.yLabel)})`);
      out.push(`| ${mdCell(c.xLabel)} | ${c.series.map(s => mdCell(s.label)).join(' | ')} |\n|---|${c.series.map(() => '---').join('|')}|\n` +
        c.categories.map((cat, i) => `| ${mdCell(cat)} | ${c.series.map(s => s.values[i]).join(' | ')} |`).join('\n'));
      if (st.text) out.push(mdParas(st.text));
      break;
    }
    default:
      out.push(mdParas(st.text));
  }
  return out.join('\n\n');
}

export function studentMd(form, mod) {
  const parts = [
    `# ${form.title}`,
    `## Reading and Writing — ${LABELS[mod.moduleId]} · Student edition`,
    `> ${form.disclaimer}`,
    `**Directions.** Each question has its own short passage, which may be a single text, a pair of texts, a poem, research notes, a table, or a graph. Read the passage and the question, then choose the one best answer from the four choices. Base every answer only on the information given. Time allowed: ${Math.round(form.timing.moduleSeconds / 60)} minutes for ${mod.items.length} questions.`,
  ];
  mod.items.forEach((it, i) => {
    parts.push('---', `### Question ${i + 1}`, stimulusMd(it.stimulus), `**${mdInline(it.stem)}**`,
      LETTERS.map(L => `${L}) ${mdInline(it.options[L])}`).join('  \n'));
  });
  return parts.join('\n\n') + '\n';
}

export function keyMd(form, taxonomy, mod) {
  const trap = id => taxonomy.trapClasses.find(t => t.id === id)?.name || id;
  const parts = [
    `# ${form.title}`,
    `## Reading and Writing — ${LABELS[mod.moduleId]} · Answer key and item notes`,
    `> ${form.disclaimer}`,
    '| Q | Key | Domain | Skill | Band | Rating | Target |\n|---|---|---|---|---|---|---|\n' +
      mod.items.map((it, i) => `| ${i + 1} | **${it.key}** | ${it.domain} | ${it.skillCode} ${it.skill} | ${it.band} | ${it.rating} | ${it.targetSeconds}s |`).join('\n'),
  ];
  mod.items.forEach((it, i) => {
    parts.push('---', `### Question ${i + 1} — ${it.id}`,
      `**Skill:** ${it.skillCode} ${it.skill} · **Difficulty:** ${it.band}, rating ${it.rating}/5 · **Target time:** ${it.targetSeconds}s · **Topic:** ${it.topic}`,
      stimulusMd(it.stimulus), `**${mdInline(it.stem)}**`,
      LETTERS.map(L => `${L}) ${mdInline(it.options[L])}`).join('  \n'),
      `**Key: ${it.key}.** ${mdInline(it.rationale)}`,
      LETTERS.filter(L => L !== it.key).map(L => `- **${L} — ${trap(it.distractors[L].trap)}:** ${mdInline(it.distractors[L].explanation)}`).join('\n'));
  });
  return parts.join('\n\n') + '\n';
}

export function blueprintMd(form, blueprint, taxonomy) {
  const parts = [
    '# Form Blueprint',
    `> ${form.disclaimer}`,
    'Generated from `data/blueprint.json` by `tools/build.mjs`. The grid is binding: `tools/validate.mjs` checks every item against it.',
    '## Structure',
    '| Domain | Module 1 | Module 2 (each route) | Total per route |\n|---|---|---|---|\n' +
      form.blueprint.domains.map(d => `| ${d.name} | ${d.m1} | ${d.m2} | ${d.total} |`).join('\n'),
    '## Difficulty',
    '| Module | Easy (1–2) | Medium (3) | Hard (4–5) |\n|---|---|---|---|\n' +
      Object.entries(form.blueprint.difficulty).map(([k, v]) => `| ${k} | ${v.Easy} | ${v.Medium} | ${v.Hard} |`).join('\n'),
    'Across the 90-item bank this is 20.0% / 45.6% / 34.4%, against the target of 20 / 45 / 35. The average of the two routes gives the same mix.',
    '## Ordering rules',
    [
      `- Domains appear in this order in every module: ${taxonomy.domainOrder.join(' → ')}.`,
      '- Within a domain group, skills are grouped and the group starts with its easiest item and ends with its hardest. The second half of each group has a higher mean rating than the first half.',
      '- No two Hard items (rating 4–5) are adjacent anywhere in a module.',
      '- Answer letters are balanced (8/8/7/7) within each module, and no letter appears three times in a row.',
      `- Target times: rating 1→35 s, 2→45 s, 3→60 s, 4→75 s, 5→90 s, plus 10 s for cross-text and quantitative-evidence items. Each module's total is within its ${form.timing.moduleSeconds / 60}-minute limit.`,
    ].join('\n'),
    '## Routing',
    `${form.routing.rule} ${form.routing.note}`,
    '## Deviations from the real exam',
    form.deviations.map(d => `- ${d}`).join('\n'),
  ];
  for (const id of MODULE_IDS) {
    const g = blueprint.modules[id];
    const secs = g.reduce((a, r) => a + r.targetSeconds, 0);
    parts.push(`## Grid — ${LABELS[id]}`, `Target-time total: ${secs} s (${(secs / 60).toFixed(1)} min).`,
      '| Pos | ID | Domain | Skill | Band | Rating | Key | Target |\n|---|---|---|---|---|---|---|---|\n' +
      g.map(r => `| ${r.position} | ${r.id} | ${r.domain} | ${r.skillCode} ${r.skill} | ${r.band} | ${r.rating} | ${r.key} | ${r.targetSeconds}s |`).join('\n'));
  }
  return parts.join('\n\n') + '\n';
}

function main() {
  const args = process.argv.slice(2);
  const dirArg = args.includes('--modules-dir') ? resolve(args[args.indexOf('--modules-dir') + 1]) : undefined;
  const data = loadAll(dirArg);
  writeFileSync(join(ROOT, 'js/data.js'), bundleJs(data));
  console.log('wrote js/data.js');
  if (args.includes('--no-docs')) return;
  mkdirSync(join(ROOT, 'docs/student-edition'), { recursive: true });
  mkdirSync(join(ROOT, 'docs/answer-key'), { recursive: true });
  for (const id of MODULE_IDS) {
    writeFileSync(join(ROOT, `docs/student-edition/${FILES[id]}.md`), studentMd(data.form, data.modules[id]));
    writeFileSync(join(ROOT, `docs/answer-key/${FILES[id]}.md`), keyMd(data.form, data.taxonomy, data.modules[id]));
  }
  writeFileSync(join(ROOT, 'docs/BLUEPRINT.md'), blueprintMd(data.form, data.blueprint, data.taxonomy));
  console.log('wrote docs/student-edition/*.md, docs/answer-key/*.md, docs/BLUEPRINT.md');

  // Deployable static site: only public files, never tools/, tests/ or .claude/.
  const dist = join(ROOT, 'dist');
  rmSync(dist, { recursive: true, force: true });
  for (const p of ['index.html', 'test.html', 'review.html', 'print.html', 'README.md', 'css', 'js', 'docs']) {
    cpSync(join(ROOT, p), join(dist, p), { recursive: true });
  }
  console.log('wrote dist/');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main();
